from rubrix._constants import DATASET_NAME_REGEX_PATTERN

API_VERSION = "v1"

TASK_DATASET_ENDPOINT = "/{task}/{name}"

TASK_PATTERN = r"[a-zA-Z-_]+"
TASKS_PATTERN = rf"({TASK_PATTERN})(,{TASK_PATTERN})*"

DATASET_NAME_PATTERN = DATASET_NAME_REGEX_PATTERN
