"""create metadata_properties table

Revision ID: 7cbcccf8b57a
Revises: 1e629a913727
Create Date: 2023-09-22 11:40:07.700301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbcccf8b57a'
down_revision = '1e629a913727'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_properties',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'dataset_id', name='metadata_property_name_dataset_id_uq')
    )
    op.create_index(op.f('ix_metadata_properties_dataset_id'), 'metadata_properties', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_metadata_properties_name'), 'metadata_properties', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_properties_name'), table_name='metadata_properties')
    op.drop_index(op.f('ix_metadata_properties_dataset_id'), table_name='metadata_properties')
    op.drop_table('metadata_properties')
    # ### end Alembic commands ###
