elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.5.3
  replicas: 1
  resources:
    requests:
      cpu: 0.25
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  javaOpts: "-Xms256m -Xmx256m"
  storage:
    size: 2Gi
service:
  type: ClusterIP
  port: 9200
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
ingress:
  enabled: true
  className: "nginx"
  host: "argilla.local"
  path: /es
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
autoscaling:
  enabled: true