{{- if and .Values.elasticsearch.useOperator }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "argilla.fullname" . }}
spec:
  version: {{ .Values.elasticsearch.version }}
  nodeSets:
  - name: default
    count: {{ .Values.elasticsearch.nodeCount }}
    config:
      node.store.allow_mmap: false
      {{- if .Values.elasticsearch.disableAuthentication }}
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
      {{- end }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage.size }}
        {{- if .Values.elasticsearch.storage.storageClass }}
        storageClassName: {{ .Values.elasticsearch.storage.storageClass }}
        {{- end }}
  {{- if .Values.elasticsearch.disableAuthentication }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  {{- end }}
  {{- with .Values.elasticsearch.resources }}
  resources:
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}