apiVersion: v1
kind: Service
metadata:
  name: {{ include "argilla.fullname" . }}
  labels:
    {{- include "argilla.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "argilla.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 6900
