name: "\U0001F195 Feature request"
description: "Share cool new ideas for the project."
title: "[FEATURE]"
labels: []
assignees: []


body:
  - type: markdown
    attributes:
      value: "Thank you for sharing your feature request! Please fill out the sections below."

  - type: textarea
    id: feature_request
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when..."
    validations:
          required: false

  - type: textarea
    id: feature_description
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: false

  - type: textarea
    id: feature_alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
