wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: huggingface
    huggingface_version: 4.2.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      4: 3.7.10
      5: 0.10.21
      6: 4.2.2
      8:
      - 1
      - 5
pipeline:
  desc: null
  value:
    features:
      char: null
      transformers: null
      word:
        embedding_dim: 50
        lowercase_tokens: false
        trainable: true
        weights_file: null
    head:
      labels:
      - HAM
      - SPAM
      type: biome.text.modules.heads.classification.text_classification.TextClassification
    name: my-first-classifier
    num_parameters: 256502
    num_trainable_parameters: 256502
    tokenizer:
      end_tokens: null
      lang: en
      max_nr_of_sentences: null
      max_sequence_length: null
      remove_space_tokens: true
      segment_sentences: false
      start_tokens: null
      text_cleaning: null
      transformers_kwargs: {}
      use_spacy_tokens: false
      use_transformers: false
trainer:
  desc: null
  value:
    batch_size: 16
    batches_per_epoch: null
    cuda_device: null
    data_bucketing: false
    grad_clipping: null
    grad_norm: null
    learning_rate_scheduler: null
    linear_decay: false
    momentum_scheduler: null
    moving_average: null
    num_epochs: 20
    num_serialized_models_to_keep: 1
    optimizer:
      type: adam
    patience: 2
    random_seed: null
    training_size: null
    use_amp: false
    validation_metric: -loss
    warmup_steps: 0
