const RECORD_STATUS = Object.freeze({
  PENDING: "PENDING",
  DISCARDED: "DISCARDED",
  SUBMITTED: "SUBMITTED",
});

const RECORD_STATUS_COLOR = Object.freeze({
  PENDING: "#b6b9ff",
  DISCARDED: "#c3c1c1",
  SUBMITTED: "#3e5cc9",
});

export { RECORD_STATUS, RECORD_STATUS_COLOR };
