import { shallowMount } from "@vue/test-utils";
import tokenClassificationGlobalLabelsComponent from "./TokenClassificationGlobalLabels.component";

let wrapper = null;
const options = {
  stubs: ["entity-label", "base-button"],
  propsData: {
    labels: [],
  },
};

beforeEach(() => {
  wrapper = shallowMount(tokenClassificationGlobalLabelsComponent, options);
});

afterEach(() => {
  wrapper.destroy();
});

describe("tokenClassificationGlobalLabelsComponent", () => {
  it("render the component", () => {
    expect(wrapper.is(tokenClassificationGlobalLabelsComponent)).toBe(true);
    expect(wrapper.findAll(".container")).toHaveLength(0);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(false);
  });
  it("render 1 label if labels.length === 1", async () => {
    const labelsOfSize1 = [
      {
        $id: '["PRODUCT","recognai.settings_tokclass_with_schema"]',
        id: "PRODUCT",
        order: 0,
        color_id: 0,
        text: "PRODUCT",
        dataset_id: "recognai.settings_tokclass_with_schema",
        is_activate: false,
        shortcut: "1",
        is_saved_in_back: true,
      },
    ];

    await wrapper.setProps({ labels: labelsOfSize1 });

    expect(wrapper.findAll(".container")).toHaveLength(1);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(false);
  });
  it("render all the labels if labels.length < MAX_LABELS_TO_SHOW", async () => {
    const labelsOfSize33 = [
      {
        $id: '["Rotura provocada","recognai.a_lot_of_labels_multi-label"]',
        id: "Rotura provocada",
        order: 0,
        color_id: 0,
        text: "Rotura provocada",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "1",
        is_saved_in_back: false,
      },
      {
        $id: '["No tiene agua","recognai.a_lot_of_labels_multi-label"]',
        id: "No tiene agua",
        order: 1,
        color_id: 1,
        text: "No tiene agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "2",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja",
        order: 2,
        color_id: 2,
        text: "Baja",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "3",
        is_saved_in_back: false,
      },
      {
        $id: '["Refacturación por fuga","recognai.a_lot_of_labels_multi-label"]',
        id: "Refacturación por fuga",
        order: 3,
        color_id: 3,
        text: "Refacturación por fuga",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "4",
        is_saved_in_back: false,
      },
      {
        $id: '["descartado","recognai.a_lot_of_labels_multi-label"]',
        id: "descartado",
        order: 4,
        color_id: 4,
        text: "descartado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "5",
        is_saved_in_back: false,
      },
      {
        $id: '["Alta","recognai.a_lot_of_labels_multi-label"]',
        id: "Alta",
        order: 5,
        color_id: 5,
        text: "Alta",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "6",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en la vía pública","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en la vía pública",
        order: 6,
        color_id: 6,
        text: "Fuga en la vía pública",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "7",
        is_saved_in_back: false,
      },
      {
        $id: '["Presupuestos","recognai.a_lot_of_labels_multi-label"]',
        id: "Presupuestos",
        order: 7,
        color_id: 7,
        text: "Presupuestos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "8",
        is_saved_in_back: false,
      },
      {
        $id: '["popopo","recognai.a_lot_of_labels_multi-label"]',
        id: "popopo",
        order: 8,
        color_id: 8,
        text: "popopo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "9",
        is_saved_in_back: false,
      },
      {
        $id: '["Información/Consultas","recognai.a_lot_of_labels_multi-label"]',
        id: "Información/Consultas",
        order: 9,
        color_id: 9,
        text: "Información/Consultas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "0",
        is_saved_in_back: false,
      },
      {
        $id: '["Problema calidad agua","recognai.a_lot_of_labels_multi-label"]',
        id: "Problema calidad agua",
        order: 10,
        color_id: 10,
        text: "Problema calidad agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Q",
        is_saved_in_back: false,
      },
      {
        $id: '["Filtración en garaje/bajo","recognai.a_lot_of_labels_multi-label"]',
        id: "Filtración en garaje/bajo",
        order: 11,
        color_id: 11,
        text: "Filtración en garaje/bajo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "W",
        is_saved_in_back: false,
      },
      {
        $id: '["Cortes falta de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Cortes falta de pago",
        order: 12,
        color_id: 12,
        text: "Cortes falta de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "E",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja presión","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja presión",
        order: 13,
        color_id: 13,
        text: "Baja presión",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "R",
        is_saved_in_back: false,
      },
      {
        $id: '["Vulnerabilidad","recognai.a_lot_of_labels_multi-label"]',
        id: "Vulnerabilidad",
        order: 14,
        color_id: 14,
        text: "Vulnerabilidad",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "T",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan cierre agua maniobras instalación abonado","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan cierre agua maniobras instalación abonado",
        order: 15,
        color_id: 15,
        text: "Solicitan cierre agua maniobras instalación abonado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Y",
        is_saved_in_back: false,
      },
      {
        $id: '["Aplazamiento de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Aplazamiento de pago",
        order: 16,
        color_id: 16,
        text: "Aplazamiento de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "U",
        is_saved_in_back: false,
      },
      {
        $id: '["Facturación errónea","recognai.a_lot_of_labels_multi-label"]',
        id: "Facturación errónea",
        order: 17,
        color_id: 17,
        text: "Facturación errónea",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "I",
        is_saved_in_back: false,
      },
      {
        $id: '["Recibos","recognai.a_lot_of_labels_multi-label"]',
        id: "Recibos",
        order: 18,
        color_id: 18,
        text: "Recibos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "O",
        is_saved_in_back: false,
      },
      {
        $id: '["Otros","recognai.a_lot_of_labels_multi-label"]',
        id: "Otros",
        order: 19,
        color_id: 19,
        text: "Otros",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "P",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en instalación interior","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en instalación interior",
        order: 20,
        color_id: 20,
        text: "Fuga en instalación interior",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "A",
        is_saved_in_back: false,
      },
      {
        $id: '["Atención recibida","recognai.a_lot_of_labels_multi-label"]',
        id: "Atención recibida",
        order: 21,
        color_id: 21,
        text: "Atención recibida",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "S",
        is_saved_in_back: false,
      },
      {
        $id: '["Reparto de correspondencia","recognai.a_lot_of_labels_multi-label"]',
        id: "Reparto de correspondencia",
        order: 22,
        color_id: 22,
        text: "Reparto de correspondencia",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "D",
        is_saved_in_back: false,
      },
      {
        $id: '["Reposición obra civil","recognai.a_lot_of_labels_multi-label"]',
        id: "Reposición obra civil",
        order: 23,
        color_id: 23,
        text: "Reposición obra civil",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "F",
        is_saved_in_back: false,
      },
      {
        $id: '["Contratación","recognai.a_lot_of_labels_multi-label"]',
        id: "Contratación",
        order: 24,
        color_id: 24,
        text: "Contratación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "G",
        is_saved_in_back: false,
      },
      {
        $id: '["Consulta administrativa oficinas","recognai.a_lot_of_labels_multi-label"]',
        id: "Consulta administrativa oficinas",
        order: 25,
        color_id: 25,
        text: "Consulta administrativa oficinas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "H",
        is_saved_in_back: false,
      },
      {
        $id: '["Error de lectura","recognai.a_lot_of_labels_multi-label"]',
        id: "Error de lectura",
        order: 26,
        color_id: 26,
        text: "Error de lectura",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "J",
        is_saved_in_back: false,
      },
      {
        $id: '["Cambio de titular","recognai.a_lot_of_labels_multi-label"]',
        id: "Cambio de titular",
        order: 27,
        color_id: 27,
        text: "Cambio de titular",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "K",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan presencia personal FACSA instalación","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan presencia personal FACSA instalación",
        order: 28,
        color_id: 28,
        text: "Solicitan presencia personal FACSA instalación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "L",
        is_saved_in_back: false,
      },
      {
        $id: '["Calidad del servicio","recognai.a_lot_of_labels_multi-label"]',
        id: "Calidad del servicio",
        order: 29,
        color_id: 29,
        text: "Calidad del servicio",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Z",
        is_saved_in_back: false,
      },
      {
        $id: '["Protección de datos","recognai.a_lot_of_labels_multi-label"]',
        id: "Protección de datos",
        order: 30,
        color_id: 30,
        text: "Protección de datos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "X",
        is_saved_in_back: false,
      },
      {
        $id: '["Funcionamiento del contador","recognai.a_lot_of_labels_multi-label"]',
        id: "Funcionamiento del contador",
        order: 31,
        color_id: 31,
        text: "Funcionamiento del contador",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "C",
        is_saved_in_back: false,
      },
      {
        $id: '["Alcantarillado/Pluviales","recognai.a_lot_of_labels_multi-label"]',
        id: "Alcantarillado/Pluviales",
        order: 32,
        color_id: 32,
        text: "Alcantarillado/Pluviales",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "V",
        is_saved_in_back: false,
      },
    ];

    await wrapper.setProps({ labels: labelsOfSize33 });

    expect(wrapper.findAll(".container")).toHaveLength(33);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(false);
  });
  it("render all the labels if labels.length === MAX_LABELS_TO_SHOW", async () => {
    const labelsOfSize40 = [
      {
        $id: '["Rotura provocada","recognai.a_lot_of_labels_multi-label"]',
        id: "Rotura provocada",
        order: 0,
        color_id: 0,
        text: "Rotura provocada",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "1",
        is_saved_in_back: false,
      },
      {
        $id: '["No tiene agua","recognai.a_lot_of_labels_multi-label"]',
        id: "No tiene agua",
        order: 1,
        color_id: 1,
        text: "No tiene agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "2",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja",
        order: 2,
        color_id: 2,
        text: "Baja",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "3",
        is_saved_in_back: false,
      },
      {
        $id: '["Refacturación por fuga","recognai.a_lot_of_labels_multi-label"]',
        id: "Refacturación por fuga",
        order: 3,
        color_id: 3,
        text: "Refacturación por fuga",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "4",
        is_saved_in_back: false,
      },
      {
        $id: '["descartado","recognai.a_lot_of_labels_multi-label"]',
        id: "descartado",
        order: 4,
        color_id: 4,
        text: "descartado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "5",
        is_saved_in_back: false,
      },
      {
        $id: '["Alta","recognai.a_lot_of_labels_multi-label"]',
        id: "Alta",
        order: 5,
        color_id: 5,
        text: "Alta",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "6",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en la vía pública","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en la vía pública",
        order: 6,
        color_id: 6,
        text: "Fuga en la vía pública",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "7",
        is_saved_in_back: false,
      },
      {
        $id: '["Presupuestos","recognai.a_lot_of_labels_multi-label"]',
        id: "Presupuestos",
        order: 7,
        color_id: 7,
        text: "Presupuestos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "8",
        is_saved_in_back: false,
      },
      {
        $id: '["popopo","recognai.a_lot_of_labels_multi-label"]',
        id: "popopo",
        order: 8,
        color_id: 8,
        text: "popopo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "9",
        is_saved_in_back: false,
      },
      {
        $id: '["Información/Consultas","recognai.a_lot_of_labels_multi-label"]',
        id: "Información/Consultas",
        order: 9,
        color_id: 9,
        text: "Información/Consultas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "0",
        is_saved_in_back: false,
      },
      {
        $id: '["Problema calidad agua","recognai.a_lot_of_labels_multi-label"]',
        id: "Problema calidad agua",
        order: 10,
        color_id: 10,
        text: "Problema calidad agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Q",
        is_saved_in_back: false,
      },
      {
        $id: '["Filtración en garaje/bajo","recognai.a_lot_of_labels_multi-label"]',
        id: "Filtración en garaje/bajo",
        order: 11,
        color_id: 11,
        text: "Filtración en garaje/bajo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "W",
        is_saved_in_back: false,
      },
      {
        $id: '["Cortes falta de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Cortes falta de pago",
        order: 12,
        color_id: 12,
        text: "Cortes falta de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "E",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja presión","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja presión",
        order: 13,
        color_id: 13,
        text: "Baja presión",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "R",
        is_saved_in_back: false,
      },
      {
        $id: '["Vulnerabilidad","recognai.a_lot_of_labels_multi-label"]',
        id: "Vulnerabilidad",
        order: 14,
        color_id: 14,
        text: "Vulnerabilidad",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "T",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan cierre agua maniobras instalación abonado","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan cierre agua maniobras instalación abonado",
        order: 15,
        color_id: 15,
        text: "Solicitan cierre agua maniobras instalación abonado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Y",
        is_saved_in_back: false,
      },
      {
        $id: '["Aplazamiento de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Aplazamiento de pago",
        order: 16,
        color_id: 16,
        text: "Aplazamiento de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "U",
        is_saved_in_back: false,
      },
      {
        $id: '["Facturación errónea","recognai.a_lot_of_labels_multi-label"]',
        id: "Facturación errónea",
        order: 17,
        color_id: 17,
        text: "Facturación errónea",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "I",
        is_saved_in_back: false,
      },
      {
        $id: '["Recibos","recognai.a_lot_of_labels_multi-label"]',
        id: "Recibos",
        order: 18,
        color_id: 18,
        text: "Recibos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "O",
        is_saved_in_back: false,
      },
      {
        $id: '["Otros","recognai.a_lot_of_labels_multi-label"]',
        id: "Otros",
        order: 19,
        color_id: 19,
        text: "Otros",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "P",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en instalación interior","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en instalación interior",
        order: 20,
        color_id: 20,
        text: "Fuga en instalación interior",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "A",
        is_saved_in_back: false,
      },
      {
        $id: '["Atención recibida","recognai.a_lot_of_labels_multi-label"]',
        id: "Atención recibida",
        order: 21,
        color_id: 21,
        text: "Atención recibida",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "S",
        is_saved_in_back: false,
      },
      {
        $id: '["Reparto de correspondencia","recognai.a_lot_of_labels_multi-label"]',
        id: "Reparto de correspondencia",
        order: 22,
        color_id: 22,
        text: "Reparto de correspondencia",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "D",
        is_saved_in_back: false,
      },
      {
        $id: '["Reposición obra civil","recognai.a_lot_of_labels_multi-label"]',
        id: "Reposición obra civil",
        order: 23,
        color_id: 23,
        text: "Reposición obra civil",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "F",
        is_saved_in_back: false,
      },
      {
        $id: '["Contratación","recognai.a_lot_of_labels_multi-label"]',
        id: "Contratación",
        order: 24,
        color_id: 24,
        text: "Contratación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "G",
        is_saved_in_back: false,
      },
      {
        $id: '["Consulta administrativa oficinas","recognai.a_lot_of_labels_multi-label"]',
        id: "Consulta administrativa oficinas",
        order: 25,
        color_id: 25,
        text: "Consulta administrativa oficinas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "H",
        is_saved_in_back: false,
      },
      {
        $id: '["Error de lectura","recognai.a_lot_of_labels_multi-label"]',
        id: "Error de lectura",
        order: 26,
        color_id: 26,
        text: "Error de lectura",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "J",
        is_saved_in_back: false,
      },
      {
        $id: '["Cambio de titular","recognai.a_lot_of_labels_multi-label"]',
        id: "Cambio de titular",
        order: 27,
        color_id: 27,
        text: "Cambio de titular",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "K",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan presencia personal FACSA instalación","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan presencia personal FACSA instalación",
        order: 28,
        color_id: 28,
        text: "Solicitan presencia personal FACSA instalación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "L",
        is_saved_in_back: false,
      },
      {
        $id: '["Calidad del servicio","recognai.a_lot_of_labels_multi-label"]',
        id: "Calidad del servicio",
        order: 29,
        color_id: 29,
        text: "Calidad del servicio",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Z",
        is_saved_in_back: false,
      },
      {
        $id: '["Protección de datos","recognai.a_lot_of_labels_multi-label"]',
        id: "Protección de datos",
        order: 30,
        color_id: 30,
        text: "Protección de datos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "X",
        is_saved_in_back: false,
      },
      {
        $id: '["Funcionamiento del contador","recognai.a_lot_of_labels_multi-label"]',
        id: "Funcionamiento del contador",
        order: 31,
        color_id: 31,
        text: "Funcionamiento del contador",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "C",
        is_saved_in_back: false,
      },
      {
        $id: '["Alcantarillado/Pluviales","recognai.a_lot_of_labels_multi-label"]',
        id: "Alcantarillado/Pluviales",
        order: 32,
        color_id: 32,
        text: "Alcantarillado/Pluviales",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "V",
        is_saved_in_back: false,
      },
      {
        $id: '["A","recognai.a_lot_of_labels_multi-label"]',
        id: "A",
        order: 33,
        color_id: 33,
        text: "A",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["B","recognai.a_lot_of_labels_multi-label"]',
        id: "B",
        order: 34,
        color_id: 34,
        text: "B",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["C","recognai.a_lot_of_labels_multi-label"]',
        id: "C",
        order: 35,
        color_id: 35,
        text: "C",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["D","recognai.a_lot_of_labels_multi-label"]',
        id: "D",
        order: 36,
        color_id: 36,
        text: "D",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["E","recognai.a_lot_of_labels_multi-label"]',
        id: "E",
        order: 37,
        color_id: 37,
        text: "E",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["F","recognai.a_lot_of_labels_multi-label"]',
        id: "F",
        order: 38,
        color_id: 38,
        text: "F",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["G","recognai.a_lot_of_labels_multi-label"]',
        id: "G",
        order: 39,
        color_id: 39,
        text: "G",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
    ];

    await wrapper.setProps({ labels: labelsOfSize40 });

    expect(wrapper.findAll(".container")).toHaveLength(40);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(false);
  });
  it("render all the labels if MAX_LABELS_TO_SHOW <= labels.length <= MAX_LABELS_TO_SHOW + OFFSET && showAllLabels === true", async () => {
    const labelsOfSize45 = [
      {
        $id: '["Rotura provocada","recognai.a_lot_of_labels_multi-label"]',
        id: "Rotura provocada",
        order: 0,
        color_id: 0,
        text: "Rotura provocada",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "1",
        is_saved_in_back: false,
      },
      {
        $id: '["No tiene agua","recognai.a_lot_of_labels_multi-label"]',
        id: "No tiene agua",
        order: 1,
        color_id: 1,
        text: "No tiene agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "2",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja",
        order: 2,
        color_id: 2,
        text: "Baja",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "3",
        is_saved_in_back: false,
      },
      {
        $id: '["Refacturación por fuga","recognai.a_lot_of_labels_multi-label"]',
        id: "Refacturación por fuga",
        order: 3,
        color_id: 3,
        text: "Refacturación por fuga",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "4",
        is_saved_in_back: false,
      },
      {
        $id: '["descartado","recognai.a_lot_of_labels_multi-label"]',
        id: "descartado",
        order: 4,
        color_id: 4,
        text: "descartado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "5",
        is_saved_in_back: false,
      },
      {
        $id: '["Alta","recognai.a_lot_of_labels_multi-label"]',
        id: "Alta",
        order: 5,
        color_id: 5,
        text: "Alta",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "6",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en la vía pública","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en la vía pública",
        order: 6,
        color_id: 6,
        text: "Fuga en la vía pública",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "7",
        is_saved_in_back: false,
      },
      {
        $id: '["Presupuestos","recognai.a_lot_of_labels_multi-label"]',
        id: "Presupuestos",
        order: 7,
        color_id: 7,
        text: "Presupuestos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "8",
        is_saved_in_back: false,
      },
      {
        $id: '["popopo","recognai.a_lot_of_labels_multi-label"]',
        id: "popopo",
        order: 8,
        color_id: 8,
        text: "popopo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "9",
        is_saved_in_back: false,
      },
      {
        $id: '["Información/Consultas","recognai.a_lot_of_labels_multi-label"]',
        id: "Información/Consultas",
        order: 9,
        color_id: 9,
        text: "Información/Consultas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "0",
        is_saved_in_back: false,
      },
      {
        $id: '["Problema calidad agua","recognai.a_lot_of_labels_multi-label"]',
        id: "Problema calidad agua",
        order: 10,
        color_id: 10,
        text: "Problema calidad agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Q",
        is_saved_in_back: false,
      },
      {
        $id: '["Filtración en garaje/bajo","recognai.a_lot_of_labels_multi-label"]',
        id: "Filtración en garaje/bajo",
        order: 11,
        color_id: 11,
        text: "Filtración en garaje/bajo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "W",
        is_saved_in_back: false,
      },
      {
        $id: '["Cortes falta de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Cortes falta de pago",
        order: 12,
        color_id: 12,
        text: "Cortes falta de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "E",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja presión","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja presión",
        order: 13,
        color_id: 13,
        text: "Baja presión",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "R",
        is_saved_in_back: false,
      },
      {
        $id: '["Vulnerabilidad","recognai.a_lot_of_labels_multi-label"]',
        id: "Vulnerabilidad",
        order: 14,
        color_id: 14,
        text: "Vulnerabilidad",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "T",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan cierre agua maniobras instalación abonado","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan cierre agua maniobras instalación abonado",
        order: 15,
        color_id: 15,
        text: "Solicitan cierre agua maniobras instalación abonado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Y",
        is_saved_in_back: false,
      },
      {
        $id: '["Aplazamiento de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Aplazamiento de pago",
        order: 16,
        color_id: 16,
        text: "Aplazamiento de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "U",
        is_saved_in_back: false,
      },
      {
        $id: '["Facturación errónea","recognai.a_lot_of_labels_multi-label"]',
        id: "Facturación errónea",
        order: 17,
        color_id: 17,
        text: "Facturación errónea",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "I",
        is_saved_in_back: false,
      },
      {
        $id: '["Recibos","recognai.a_lot_of_labels_multi-label"]',
        id: "Recibos",
        order: 18,
        color_id: 18,
        text: "Recibos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "O",
        is_saved_in_back: false,
      },
      {
        $id: '["Otros","recognai.a_lot_of_labels_multi-label"]',
        id: "Otros",
        order: 19,
        color_id: 19,
        text: "Otros",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "P",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en instalación interior","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en instalación interior",
        order: 20,
        color_id: 20,
        text: "Fuga en instalación interior",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "A",
        is_saved_in_back: false,
      },
      {
        $id: '["Atención recibida","recognai.a_lot_of_labels_multi-label"]',
        id: "Atención recibida",
        order: 21,
        color_id: 21,
        text: "Atención recibida",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "S",
        is_saved_in_back: false,
      },
      {
        $id: '["Reparto de correspondencia","recognai.a_lot_of_labels_multi-label"]',
        id: "Reparto de correspondencia",
        order: 22,
        color_id: 22,
        text: "Reparto de correspondencia",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "D",
        is_saved_in_back: false,
      },
      {
        $id: '["Reposición obra civil","recognai.a_lot_of_labels_multi-label"]',
        id: "Reposición obra civil",
        order: 23,
        color_id: 23,
        text: "Reposición obra civil",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "F",
        is_saved_in_back: false,
      },
      {
        $id: '["Contratación","recognai.a_lot_of_labels_multi-label"]',
        id: "Contratación",
        order: 24,
        color_id: 24,
        text: "Contratación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "G",
        is_saved_in_back: false,
      },
      {
        $id: '["Consulta administrativa oficinas","recognai.a_lot_of_labels_multi-label"]',
        id: "Consulta administrativa oficinas",
        order: 25,
        color_id: 25,
        text: "Consulta administrativa oficinas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "H",
        is_saved_in_back: false,
      },
      {
        $id: '["Error de lectura","recognai.a_lot_of_labels_multi-label"]',
        id: "Error de lectura",
        order: 26,
        color_id: 26,
        text: "Error de lectura",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "J",
        is_saved_in_back: false,
      },
      {
        $id: '["Cambio de titular","recognai.a_lot_of_labels_multi-label"]',
        id: "Cambio de titular",
        order: 27,
        color_id: 27,
        text: "Cambio de titular",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "K",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan presencia personal FACSA instalación","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan presencia personal FACSA instalación",
        order: 28,
        color_id: 28,
        text: "Solicitan presencia personal FACSA instalación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "L",
        is_saved_in_back: false,
      },
      {
        $id: '["Calidad del servicio","recognai.a_lot_of_labels_multi-label"]',
        id: "Calidad del servicio",
        order: 29,
        color_id: 29,
        text: "Calidad del servicio",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Z",
        is_saved_in_back: false,
      },
      {
        $id: '["Protección de datos","recognai.a_lot_of_labels_multi-label"]',
        id: "Protección de datos",
        order: 30,
        color_id: 30,
        text: "Protección de datos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "X",
        is_saved_in_back: false,
      },
      {
        $id: '["Funcionamiento del contador","recognai.a_lot_of_labels_multi-label"]',
        id: "Funcionamiento del contador",
        order: 31,
        color_id: 31,
        text: "Funcionamiento del contador",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "C",
        is_saved_in_back: false,
      },
      {
        $id: '["Alcantarillado/Pluviales","recognai.a_lot_of_labels_multi-label"]',
        id: "Alcantarillado/Pluviales",
        order: 32,
        color_id: 32,
        text: "Alcantarillado/Pluviales",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "V",
        is_saved_in_back: false,
      },
      {
        $id: '["A","recognai.a_lot_of_labels_multi-label"]',
        id: "A",
        order: 33,
        color_id: 33,
        text: "A",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["B","recognai.a_lot_of_labels_multi-label"]',
        id: "B",
        order: 34,
        color_id: 34,
        text: "B",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["C","recognai.a_lot_of_labels_multi-label"]',
        id: "C",
        order: 35,
        color_id: 35,
        text: "C",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["D","recognai.a_lot_of_labels_multi-label"]',
        id: "D",
        order: 36,
        color_id: 36,
        text: "D",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["E","recognai.a_lot_of_labels_multi-label"]',
        id: "E",
        order: 37,
        color_id: 37,
        text: "E",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["F","recognai.a_lot_of_labels_multi-label"]',
        id: "F",
        order: 38,
        color_id: 38,
        text: "F",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["G","recognai.a_lot_of_labels_multi-label"]',
        id: "G",
        order: 39,
        color_id: 39,
        text: "G",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["H","recognai.a_lot_of_labels_multi-label"]',
        id: "H",
        order: 40,
        color_id: 40,
        text: "H",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["I","recognai.a_lot_of_labels_multi-label"]',
        id: "I",
        order: 41,
        color_id: 41,
        text: "I",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["J","recognai.a_lot_of_labels_multi-label"]',
        id: "J",
        order: 42,
        color_id: 42,
        text: "J",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["K","recognai.a_lot_of_labels_multi-label"]',
        id: "K",
        order: 43,
        color_id: 43,
        text: "K",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["L","recognai.a_lot_of_labels_multi-label"]',
        id: "L",
        order: 44,
        color_id: 44,
        text: "L",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
    ];

    await wrapper.setProps({ labels: labelsOfSize45 });
    await wrapper.setProps({ showAllLabels: true });

    expect(wrapper.findAll(".container")).toHaveLength(45);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(false);
  });
  it("render all the labels if MAX_LABELS_TO_SHOW <= labels.length <= MAX_LABELS_TO_SHOW + OFFSET && showAllLabels === false", async () => {
    const labelsOfSize45 = [
      {
        $id: '["Rotura provocada","recognai.a_lot_of_labels_multi-label"]',
        id: "Rotura provocada",
        order: 0,
        color_id: 0,
        text: "Rotura provocada",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "1",
        is_saved_in_back: false,
      },
      {
        $id: '["No tiene agua","recognai.a_lot_of_labels_multi-label"]',
        id: "No tiene agua",
        order: 1,
        color_id: 1,
        text: "No tiene agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "2",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja",
        order: 2,
        color_id: 2,
        text: "Baja",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "3",
        is_saved_in_back: false,
      },
      {
        $id: '["Refacturación por fuga","recognai.a_lot_of_labels_multi-label"]',
        id: "Refacturación por fuga",
        order: 3,
        color_id: 3,
        text: "Refacturación por fuga",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "4",
        is_saved_in_back: false,
      },
      {
        $id: '["descartado","recognai.a_lot_of_labels_multi-label"]',
        id: "descartado",
        order: 4,
        color_id: 4,
        text: "descartado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "5",
        is_saved_in_back: false,
      },
      {
        $id: '["Alta","recognai.a_lot_of_labels_multi-label"]',
        id: "Alta",
        order: 5,
        color_id: 5,
        text: "Alta",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "6",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en la vía pública","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en la vía pública",
        order: 6,
        color_id: 6,
        text: "Fuga en la vía pública",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "7",
        is_saved_in_back: false,
      },
      {
        $id: '["Presupuestos","recognai.a_lot_of_labels_multi-label"]',
        id: "Presupuestos",
        order: 7,
        color_id: 7,
        text: "Presupuestos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "8",
        is_saved_in_back: false,
      },
      {
        $id: '["popopo","recognai.a_lot_of_labels_multi-label"]',
        id: "popopo",
        order: 8,
        color_id: 8,
        text: "popopo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "9",
        is_saved_in_back: false,
      },
      {
        $id: '["Información/Consultas","recognai.a_lot_of_labels_multi-label"]',
        id: "Información/Consultas",
        order: 9,
        color_id: 9,
        text: "Información/Consultas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "0",
        is_saved_in_back: false,
      },
      {
        $id: '["Problema calidad agua","recognai.a_lot_of_labels_multi-label"]',
        id: "Problema calidad agua",
        order: 10,
        color_id: 10,
        text: "Problema calidad agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Q",
        is_saved_in_back: false,
      },
      {
        $id: '["Filtración en garaje/bajo","recognai.a_lot_of_labels_multi-label"]',
        id: "Filtración en garaje/bajo",
        order: 11,
        color_id: 11,
        text: "Filtración en garaje/bajo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "W",
        is_saved_in_back: false,
      },
      {
        $id: '["Cortes falta de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Cortes falta de pago",
        order: 12,
        color_id: 12,
        text: "Cortes falta de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "E",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja presión","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja presión",
        order: 13,
        color_id: 13,
        text: "Baja presión",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "R",
        is_saved_in_back: false,
      },
      {
        $id: '["Vulnerabilidad","recognai.a_lot_of_labels_multi-label"]',
        id: "Vulnerabilidad",
        order: 14,
        color_id: 14,
        text: "Vulnerabilidad",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "T",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan cierre agua maniobras instalación abonado","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan cierre agua maniobras instalación abonado",
        order: 15,
        color_id: 15,
        text: "Solicitan cierre agua maniobras instalación abonado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Y",
        is_saved_in_back: false,
      },
      {
        $id: '["Aplazamiento de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Aplazamiento de pago",
        order: 16,
        color_id: 16,
        text: "Aplazamiento de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "U",
        is_saved_in_back: false,
      },
      {
        $id: '["Facturación errónea","recognai.a_lot_of_labels_multi-label"]',
        id: "Facturación errónea",
        order: 17,
        color_id: 17,
        text: "Facturación errónea",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "I",
        is_saved_in_back: false,
      },
      {
        $id: '["Recibos","recognai.a_lot_of_labels_multi-label"]',
        id: "Recibos",
        order: 18,
        color_id: 18,
        text: "Recibos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "O",
        is_saved_in_back: false,
      },
      {
        $id: '["Otros","recognai.a_lot_of_labels_multi-label"]',
        id: "Otros",
        order: 19,
        color_id: 19,
        text: "Otros",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "P",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en instalación interior","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en instalación interior",
        order: 20,
        color_id: 20,
        text: "Fuga en instalación interior",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "A",
        is_saved_in_back: false,
      },
      {
        $id: '["Atención recibida","recognai.a_lot_of_labels_multi-label"]',
        id: "Atención recibida",
        order: 21,
        color_id: 21,
        text: "Atención recibida",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "S",
        is_saved_in_back: false,
      },
      {
        $id: '["Reparto de correspondencia","recognai.a_lot_of_labels_multi-label"]',
        id: "Reparto de correspondencia",
        order: 22,
        color_id: 22,
        text: "Reparto de correspondencia",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "D",
        is_saved_in_back: false,
      },
      {
        $id: '["Reposición obra civil","recognai.a_lot_of_labels_multi-label"]',
        id: "Reposición obra civil",
        order: 23,
        color_id: 23,
        text: "Reposición obra civil",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "F",
        is_saved_in_back: false,
      },
      {
        $id: '["Contratación","recognai.a_lot_of_labels_multi-label"]',
        id: "Contratación",
        order: 24,
        color_id: 24,
        text: "Contratación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "G",
        is_saved_in_back: false,
      },
      {
        $id: '["Consulta administrativa oficinas","recognai.a_lot_of_labels_multi-label"]',
        id: "Consulta administrativa oficinas",
        order: 25,
        color_id: 25,
        text: "Consulta administrativa oficinas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "H",
        is_saved_in_back: false,
      },
      {
        $id: '["Error de lectura","recognai.a_lot_of_labels_multi-label"]',
        id: "Error de lectura",
        order: 26,
        color_id: 26,
        text: "Error de lectura",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "J",
        is_saved_in_back: false,
      },
      {
        $id: '["Cambio de titular","recognai.a_lot_of_labels_multi-label"]',
        id: "Cambio de titular",
        order: 27,
        color_id: 27,
        text: "Cambio de titular",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "K",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan presencia personal FACSA instalación","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan presencia personal FACSA instalación",
        order: 28,
        color_id: 28,
        text: "Solicitan presencia personal FACSA instalación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "L",
        is_saved_in_back: false,
      },
      {
        $id: '["Calidad del servicio","recognai.a_lot_of_labels_multi-label"]',
        id: "Calidad del servicio",
        order: 29,
        color_id: 29,
        text: "Calidad del servicio",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Z",
        is_saved_in_back: false,
      },
      {
        $id: '["Protección de datos","recognai.a_lot_of_labels_multi-label"]',
        id: "Protección de datos",
        order: 30,
        color_id: 30,
        text: "Protección de datos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "X",
        is_saved_in_back: false,
      },
      {
        $id: '["Funcionamiento del contador","recognai.a_lot_of_labels_multi-label"]',
        id: "Funcionamiento del contador",
        order: 31,
        color_id: 31,
        text: "Funcionamiento del contador",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "C",
        is_saved_in_back: false,
      },
      {
        $id: '["Alcantarillado/Pluviales","recognai.a_lot_of_labels_multi-label"]',
        id: "Alcantarillado/Pluviales",
        order: 32,
        color_id: 32,
        text: "Alcantarillado/Pluviales",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "V",
        is_saved_in_back: false,
      },
      {
        $id: '["A","recognai.a_lot_of_labels_multi-label"]',
        id: "A",
        order: 33,
        color_id: 33,
        text: "A",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["B","recognai.a_lot_of_labels_multi-label"]',
        id: "B",
        order: 34,
        color_id: 34,
        text: "B",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["C","recognai.a_lot_of_labels_multi-label"]',
        id: "C",
        order: 35,
        color_id: 35,
        text: "C",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["D","recognai.a_lot_of_labels_multi-label"]',
        id: "D",
        order: 36,
        color_id: 36,
        text: "D",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["E","recognai.a_lot_of_labels_multi-label"]',
        id: "E",
        order: 37,
        color_id: 37,
        text: "E",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["F","recognai.a_lot_of_labels_multi-label"]',
        id: "F",
        order: 38,
        color_id: 38,
        text: "F",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["G","recognai.a_lot_of_labels_multi-label"]',
        id: "G",
        order: 39,
        color_id: 39,
        text: "G",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["H","recognai.a_lot_of_labels_multi-label"]',
        id: "H",
        order: 40,
        color_id: 40,
        text: "H",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["I","recognai.a_lot_of_labels_multi-label"]',
        id: "I",
        order: 41,
        color_id: 41,
        text: "I",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["J","recognai.a_lot_of_labels_multi-label"]',
        id: "J",
        order: 42,
        color_id: 42,
        text: "J",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["K","recognai.a_lot_of_labels_multi-label"]',
        id: "K",
        order: 43,
        color_id: 43,
        text: "K",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["L","recognai.a_lot_of_labels_multi-label"]',
        id: "L",
        order: 44,
        color_id: 44,
        text: "L",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
    ];

    await wrapper.setProps({ labels: labelsOfSize45 });
    await wrapper.setProps({ showAllLabels: false });

    expect(wrapper.findAll(".container")).toHaveLength(45);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(false);
  });
  it("render all the labels if labels.length > MAX_LABELS_TO_SHOW + OFFSET && showAllLabels === true", async () => {
    const labelsOfSize46 = [
      {
        $id: '["Rotura provocada","recognai.a_lot_of_labels_multi-label"]',
        id: "Rotura provocada",
        order: 0,
        color_id: 0,
        text: "Rotura provocada",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "1",
        is_saved_in_back: false,
      },
      {
        $id: '["No tiene agua","recognai.a_lot_of_labels_multi-label"]',
        id: "No tiene agua",
        order: 1,
        color_id: 1,
        text: "No tiene agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "2",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja",
        order: 2,
        color_id: 2,
        text: "Baja",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "3",
        is_saved_in_back: false,
      },
      {
        $id: '["Refacturación por fuga","recognai.a_lot_of_labels_multi-label"]',
        id: "Refacturación por fuga",
        order: 3,
        color_id: 3,
        text: "Refacturación por fuga",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "4",
        is_saved_in_back: false,
      },
      {
        $id: '["descartado","recognai.a_lot_of_labels_multi-label"]',
        id: "descartado",
        order: 4,
        color_id: 4,
        text: "descartado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "5",
        is_saved_in_back: false,
      },
      {
        $id: '["Alta","recognai.a_lot_of_labels_multi-label"]',
        id: "Alta",
        order: 5,
        color_id: 5,
        text: "Alta",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "6",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en la vía pública","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en la vía pública",
        order: 6,
        color_id: 6,
        text: "Fuga en la vía pública",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "7",
        is_saved_in_back: false,
      },
      {
        $id: '["Presupuestos","recognai.a_lot_of_labels_multi-label"]',
        id: "Presupuestos",
        order: 7,
        color_id: 7,
        text: "Presupuestos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "8",
        is_saved_in_back: false,
      },
      {
        $id: '["popopo","recognai.a_lot_of_labels_multi-label"]',
        id: "popopo",
        order: 8,
        color_id: 8,
        text: "popopo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "9",
        is_saved_in_back: false,
      },
      {
        $id: '["Información/Consultas","recognai.a_lot_of_labels_multi-label"]',
        id: "Información/Consultas",
        order: 9,
        color_id: 9,
        text: "Información/Consultas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "0",
        is_saved_in_back: false,
      },
      {
        $id: '["Problema calidad agua","recognai.a_lot_of_labels_multi-label"]',
        id: "Problema calidad agua",
        order: 10,
        color_id: 10,
        text: "Problema calidad agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Q",
        is_saved_in_back: false,
      },
      {
        $id: '["Filtración en garaje/bajo","recognai.a_lot_of_labels_multi-label"]',
        id: "Filtración en garaje/bajo",
        order: 11,
        color_id: 11,
        text: "Filtración en garaje/bajo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "W",
        is_saved_in_back: false,
      },
      {
        $id: '["Cortes falta de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Cortes falta de pago",
        order: 12,
        color_id: 12,
        text: "Cortes falta de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "E",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja presión","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja presión",
        order: 13,
        color_id: 13,
        text: "Baja presión",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "R",
        is_saved_in_back: false,
      },
      {
        $id: '["Vulnerabilidad","recognai.a_lot_of_labels_multi-label"]',
        id: "Vulnerabilidad",
        order: 14,
        color_id: 14,
        text: "Vulnerabilidad",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "T",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan cierre agua maniobras instalación abonado","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan cierre agua maniobras instalación abonado",
        order: 15,
        color_id: 15,
        text: "Solicitan cierre agua maniobras instalación abonado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Y",
        is_saved_in_back: false,
      },
      {
        $id: '["Aplazamiento de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Aplazamiento de pago",
        order: 16,
        color_id: 16,
        text: "Aplazamiento de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "U",
        is_saved_in_back: false,
      },
      {
        $id: '["Facturación errónea","recognai.a_lot_of_labels_multi-label"]',
        id: "Facturación errónea",
        order: 17,
        color_id: 17,
        text: "Facturación errónea",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "I",
        is_saved_in_back: false,
      },
      {
        $id: '["Recibos","recognai.a_lot_of_labels_multi-label"]',
        id: "Recibos",
        order: 18,
        color_id: 18,
        text: "Recibos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "O",
        is_saved_in_back: false,
      },
      {
        $id: '["Otros","recognai.a_lot_of_labels_multi-label"]',
        id: "Otros",
        order: 19,
        color_id: 19,
        text: "Otros",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "P",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en instalación interior","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en instalación interior",
        order: 20,
        color_id: 20,
        text: "Fuga en instalación interior",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "A",
        is_saved_in_back: false,
      },
      {
        $id: '["Atención recibida","recognai.a_lot_of_labels_multi-label"]',
        id: "Atención recibida",
        order: 21,
        color_id: 21,
        text: "Atención recibida",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "S",
        is_saved_in_back: false,
      },
      {
        $id: '["Reparto de correspondencia","recognai.a_lot_of_labels_multi-label"]',
        id: "Reparto de correspondencia",
        order: 22,
        color_id: 22,
        text: "Reparto de correspondencia",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "D",
        is_saved_in_back: false,
      },
      {
        $id: '["Reposición obra civil","recognai.a_lot_of_labels_multi-label"]',
        id: "Reposición obra civil",
        order: 23,
        color_id: 23,
        text: "Reposición obra civil",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "F",
        is_saved_in_back: false,
      },
      {
        $id: '["Contratación","recognai.a_lot_of_labels_multi-label"]',
        id: "Contratación",
        order: 24,
        color_id: 24,
        text: "Contratación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "G",
        is_saved_in_back: false,
      },
      {
        $id: '["Consulta administrativa oficinas","recognai.a_lot_of_labels_multi-label"]',
        id: "Consulta administrativa oficinas",
        order: 25,
        color_id: 25,
        text: "Consulta administrativa oficinas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "H",
        is_saved_in_back: false,
      },
      {
        $id: '["Error de lectura","recognai.a_lot_of_labels_multi-label"]',
        id: "Error de lectura",
        order: 26,
        color_id: 26,
        text: "Error de lectura",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "J",
        is_saved_in_back: false,
      },
      {
        $id: '["Cambio de titular","recognai.a_lot_of_labels_multi-label"]',
        id: "Cambio de titular",
        order: 27,
        color_id: 27,
        text: "Cambio de titular",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "K",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan presencia personal FACSA instalación","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan presencia personal FACSA instalación",
        order: 28,
        color_id: 28,
        text: "Solicitan presencia personal FACSA instalación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "L",
        is_saved_in_back: false,
      },
      {
        $id: '["Calidad del servicio","recognai.a_lot_of_labels_multi-label"]',
        id: "Calidad del servicio",
        order: 29,
        color_id: 29,
        text: "Calidad del servicio",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Z",
        is_saved_in_back: false,
      },
      {
        $id: '["Protección de datos","recognai.a_lot_of_labels_multi-label"]',
        id: "Protección de datos",
        order: 30,
        color_id: 30,
        text: "Protección de datos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "X",
        is_saved_in_back: false,
      },
      {
        $id: '["Funcionamiento del contador","recognai.a_lot_of_labels_multi-label"]',
        id: "Funcionamiento del contador",
        order: 31,
        color_id: 31,
        text: "Funcionamiento del contador",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "C",
        is_saved_in_back: false,
      },
      {
        $id: '["Alcantarillado/Pluviales","recognai.a_lot_of_labels_multi-label"]',
        id: "Alcantarillado/Pluviales",
        order: 32,
        color_id: 32,
        text: "Alcantarillado/Pluviales",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "V",
        is_saved_in_back: false,
      },
      {
        $id: '["A","recognai.a_lot_of_labels_multi-label"]',
        id: "A",
        order: 33,
        color_id: 33,
        text: "A",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["B","recognai.a_lot_of_labels_multi-label"]',
        id: "B",
        order: 34,
        color_id: 34,
        text: "B",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["C","recognai.a_lot_of_labels_multi-label"]',
        id: "C",
        order: 35,
        color_id: 35,
        text: "C",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["D","recognai.a_lot_of_labels_multi-label"]',
        id: "D",
        order: 36,
        color_id: 36,
        text: "D",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["E","recognai.a_lot_of_labels_multi-label"]',
        id: "E",
        order: 37,
        color_id: 37,
        text: "E",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["F","recognai.a_lot_of_labels_multi-label"]',
        id: "F",
        order: 38,
        color_id: 38,
        text: "F",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["G","recognai.a_lot_of_labels_multi-label"]',
        id: "G",
        order: 39,
        color_id: 39,
        text: "G",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["H","recognai.a_lot_of_labels_multi-label"]',
        id: "H",
        order: 40,
        color_id: 40,
        text: "H",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["I","recognai.a_lot_of_labels_multi-label"]',
        id: "I",
        order: 41,
        color_id: 41,
        text: "I",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["J","recognai.a_lot_of_labels_multi-label"]',
        id: "J",
        order: 42,
        color_id: 42,
        text: "J",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["K","recognai.a_lot_of_labels_multi-label"]',
        id: "K",
        order: 43,
        color_id: 43,
        text: "K",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["L","recognai.a_lot_of_labels_multi-label"]',
        id: "L",
        order: 44,
        color_id: 44,
        text: "L",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["M","recognai.a_lot_of_labels_multi-label"]',
        id: "M",
        order: 45,
        color_id: 45,
        text: "M",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["n","recognai.a_lot_of_labels_multi-label"]',
        id: "n",
        order: 46,
        color_id: 46,
        text: "n",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
    ];
    await wrapper.setProps({ labels: labelsOfSize46 });
    await wrapper.setProps({ showAllLabels: true });

    expect(wrapper.findAll(".container")).toHaveLength(47);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(true);
  });
  it("render MAX_LABELS_TO_SHOW number of labels if labels.length > MAX_LABELS_TO_SHOW + OFFSET && showAllLabels === false", async () => {
    const labelsOfSize46 = [
      {
        $id: '["Rotura provocada","recognai.a_lot_of_labels_multi-label"]',
        id: "Rotura provocada",
        order: 0,
        color_id: 0,
        text: "Rotura provocada",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "1",
        is_saved_in_back: false,
      },
      {
        $id: '["No tiene agua","recognai.a_lot_of_labels_multi-label"]',
        id: "No tiene agua",
        order: 1,
        color_id: 1,
        text: "No tiene agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "2",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja",
        order: 2,
        color_id: 2,
        text: "Baja",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "3",
        is_saved_in_back: false,
      },
      {
        $id: '["Refacturación por fuga","recognai.a_lot_of_labels_multi-label"]',
        id: "Refacturación por fuga",
        order: 3,
        color_id: 3,
        text: "Refacturación por fuga",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "4",
        is_saved_in_back: false,
      },
      {
        $id: '["descartado","recognai.a_lot_of_labels_multi-label"]',
        id: "descartado",
        order: 4,
        color_id: 4,
        text: "descartado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "5",
        is_saved_in_back: false,
      },
      {
        $id: '["Alta","recognai.a_lot_of_labels_multi-label"]',
        id: "Alta",
        order: 5,
        color_id: 5,
        text: "Alta",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "6",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en la vía pública","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en la vía pública",
        order: 6,
        color_id: 6,
        text: "Fuga en la vía pública",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "7",
        is_saved_in_back: false,
      },
      {
        $id: '["Presupuestos","recognai.a_lot_of_labels_multi-label"]',
        id: "Presupuestos",
        order: 7,
        color_id: 7,
        text: "Presupuestos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "8",
        is_saved_in_back: false,
      },
      {
        $id: '["popopo","recognai.a_lot_of_labels_multi-label"]',
        id: "popopo",
        order: 8,
        color_id: 8,
        text: "popopo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "9",
        is_saved_in_back: false,
      },
      {
        $id: '["Información/Consultas","recognai.a_lot_of_labels_multi-label"]',
        id: "Información/Consultas",
        order: 9,
        color_id: 9,
        text: "Información/Consultas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "0",
        is_saved_in_back: false,
      },
      {
        $id: '["Problema calidad agua","recognai.a_lot_of_labels_multi-label"]',
        id: "Problema calidad agua",
        order: 10,
        color_id: 10,
        text: "Problema calidad agua",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Q",
        is_saved_in_back: false,
      },
      {
        $id: '["Filtración en garaje/bajo","recognai.a_lot_of_labels_multi-label"]',
        id: "Filtración en garaje/bajo",
        order: 11,
        color_id: 11,
        text: "Filtración en garaje/bajo",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "W",
        is_saved_in_back: false,
      },
      {
        $id: '["Cortes falta de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Cortes falta de pago",
        order: 12,
        color_id: 12,
        text: "Cortes falta de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "E",
        is_saved_in_back: false,
      },
      {
        $id: '["Baja presión","recognai.a_lot_of_labels_multi-label"]',
        id: "Baja presión",
        order: 13,
        color_id: 13,
        text: "Baja presión",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "R",
        is_saved_in_back: false,
      },
      {
        $id: '["Vulnerabilidad","recognai.a_lot_of_labels_multi-label"]',
        id: "Vulnerabilidad",
        order: 14,
        color_id: 14,
        text: "Vulnerabilidad",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "T",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan cierre agua maniobras instalación abonado","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan cierre agua maniobras instalación abonado",
        order: 15,
        color_id: 15,
        text: "Solicitan cierre agua maniobras instalación abonado",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Y",
        is_saved_in_back: false,
      },
      {
        $id: '["Aplazamiento de pago","recognai.a_lot_of_labels_multi-label"]',
        id: "Aplazamiento de pago",
        order: 16,
        color_id: 16,
        text: "Aplazamiento de pago",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "U",
        is_saved_in_back: false,
      },
      {
        $id: '["Facturación errónea","recognai.a_lot_of_labels_multi-label"]',
        id: "Facturación errónea",
        order: 17,
        color_id: 17,
        text: "Facturación errónea",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "I",
        is_saved_in_back: false,
      },
      {
        $id: '["Recibos","recognai.a_lot_of_labels_multi-label"]',
        id: "Recibos",
        order: 18,
        color_id: 18,
        text: "Recibos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "O",
        is_saved_in_back: false,
      },
      {
        $id: '["Otros","recognai.a_lot_of_labels_multi-label"]',
        id: "Otros",
        order: 19,
        color_id: 19,
        text: "Otros",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "P",
        is_saved_in_back: false,
      },
      {
        $id: '["Fuga en instalación interior","recognai.a_lot_of_labels_multi-label"]',
        id: "Fuga en instalación interior",
        order: 20,
        color_id: 20,
        text: "Fuga en instalación interior",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "A",
        is_saved_in_back: false,
      },
      {
        $id: '["Atención recibida","recognai.a_lot_of_labels_multi-label"]',
        id: "Atención recibida",
        order: 21,
        color_id: 21,
        text: "Atención recibida",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "S",
        is_saved_in_back: false,
      },
      {
        $id: '["Reparto de correspondencia","recognai.a_lot_of_labels_multi-label"]',
        id: "Reparto de correspondencia",
        order: 22,
        color_id: 22,
        text: "Reparto de correspondencia",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "D",
        is_saved_in_back: false,
      },
      {
        $id: '["Reposición obra civil","recognai.a_lot_of_labels_multi-label"]',
        id: "Reposición obra civil",
        order: 23,
        color_id: 23,
        text: "Reposición obra civil",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "F",
        is_saved_in_back: false,
      },
      {
        $id: '["Contratación","recognai.a_lot_of_labels_multi-label"]',
        id: "Contratación",
        order: 24,
        color_id: 24,
        text: "Contratación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "G",
        is_saved_in_back: false,
      },
      {
        $id: '["Consulta administrativa oficinas","recognai.a_lot_of_labels_multi-label"]',
        id: "Consulta administrativa oficinas",
        order: 25,
        color_id: 25,
        text: "Consulta administrativa oficinas",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "H",
        is_saved_in_back: false,
      },
      {
        $id: '["Error de lectura","recognai.a_lot_of_labels_multi-label"]',
        id: "Error de lectura",
        order: 26,
        color_id: 26,
        text: "Error de lectura",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "J",
        is_saved_in_back: false,
      },
      {
        $id: '["Cambio de titular","recognai.a_lot_of_labels_multi-label"]',
        id: "Cambio de titular",
        order: 27,
        color_id: 27,
        text: "Cambio de titular",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "K",
        is_saved_in_back: false,
      },
      {
        $id: '["Solicitan presencia personal FACSA instalación","recognai.a_lot_of_labels_multi-label"]',
        id: "Solicitan presencia personal FACSA instalación",
        order: 28,
        color_id: 28,
        text: "Solicitan presencia personal FACSA instalación",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "L",
        is_saved_in_back: false,
      },
      {
        $id: '["Calidad del servicio","recognai.a_lot_of_labels_multi-label"]',
        id: "Calidad del servicio",
        order: 29,
        color_id: 29,
        text: "Calidad del servicio",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "Z",
        is_saved_in_back: false,
      },
      {
        $id: '["Protección de datos","recognai.a_lot_of_labels_multi-label"]',
        id: "Protección de datos",
        order: 30,
        color_id: 30,
        text: "Protección de datos",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "X",
        is_saved_in_back: false,
      },
      {
        $id: '["Funcionamiento del contador","recognai.a_lot_of_labels_multi-label"]',
        id: "Funcionamiento del contador",
        order: 31,
        color_id: 31,
        text: "Funcionamiento del contador",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "C",
        is_saved_in_back: false,
      },
      {
        $id: '["Alcantarillado/Pluviales","recognai.a_lot_of_labels_multi-label"]',
        id: "Alcantarillado/Pluviales",
        order: 32,
        color_id: 32,
        text: "Alcantarillado/Pluviales",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: "V",
        is_saved_in_back: false,
      },
      {
        $id: '["A","recognai.a_lot_of_labels_multi-label"]',
        id: "A",
        order: 33,
        color_id: 33,
        text: "A",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["B","recognai.a_lot_of_labels_multi-label"]',
        id: "B",
        order: 34,
        color_id: 34,
        text: "B",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["C","recognai.a_lot_of_labels_multi-label"]',
        id: "C",
        order: 35,
        color_id: 35,
        text: "C",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["D","recognai.a_lot_of_labels_multi-label"]',
        id: "D",
        order: 36,
        color_id: 36,
        text: "D",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["E","recognai.a_lot_of_labels_multi-label"]',
        id: "E",
        order: 37,
        color_id: 37,
        text: "E",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["F","recognai.a_lot_of_labels_multi-label"]',
        id: "F",
        order: 38,
        color_id: 38,
        text: "F",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["G","recognai.a_lot_of_labels_multi-label"]',
        id: "G",
        order: 39,
        color_id: 39,
        text: "G",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["H","recognai.a_lot_of_labels_multi-label"]',
        id: "H",
        order: 40,
        color_id: 40,
        text: "H",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["I","recognai.a_lot_of_labels_multi-label"]',
        id: "I",
        order: 41,
        color_id: 41,
        text: "I",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["J","recognai.a_lot_of_labels_multi-label"]',
        id: "J",
        order: 42,
        color_id: 42,
        text: "J",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["K","recognai.a_lot_of_labels_multi-label"]',
        id: "K",
        order: 43,
        color_id: 43,
        text: "K",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["L","recognai.a_lot_of_labels_multi-label"]',
        id: "L",
        order: 44,
        color_id: 44,
        text: "L",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["M","recognai.a_lot_of_labels_multi-label"]',
        id: "M",
        order: 45,
        color_id: 45,
        text: "M",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
      {
        $id: '["n","recognai.a_lot_of_labels_multi-label"]',
        id: "n",
        order: 46,
        color_id: 46,
        text: "n",
        dataset_id: "recognai.a_lot_of_labels_multi-label",
        is_activate: false,
        shortcut: null,
        is_saved_in_back: false,
      },
    ];
    await wrapper.setProps({ labels: labelsOfSize46 });
    await wrapper.setProps({ showAllLabels: false });

    expect(wrapper.findAll(".container")).toHaveLength(40);
    expect(wrapper.find("#showLessMoreButtonId").exists()).toBe(true);
  });
});
