name: Just ignore me

on:
  release:
    types:
      - "published"

  push:
    branches:
      - "main"
      - "develop"
      - "releases/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "releases/**"
      - "feature/**"
      - "feat/**"

jobs:

  test-opensearch:
    name: Test with OpenSearch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 1.3, 2.3 ]
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Setup OpenSearch 🔎
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: ${{ matrix.version }}
          config: |
            http.port: 9200

      - name: Run tests 📈
        run: curl -XGET localhost:9200

